### ISSUE TITLE
See changed files 1.3.0-rc.0 to 1.3.0-rc.2 fails

### ISSUE THREAD

**Issue by udaysinghcode** [navinpeiris/phoenix-diff#6]
Hey @navinpeiris 

Love this tool, really simple and great for upgrading. I just noticed a small bug.

If you're on this page:
https://www.phoenixdiff.org/d2h-053433?source=1.3.0-rc.0&target=1.3.0-rc.2

And then click "show" for Files changed, the interaction one would expect is that test/support/data_case.ex for example should open a view showing the file.

Unfortunately, clicking the link links you here: 

https://www.phoenixdiff.org/d2h-053433?source=1.2.1&target=1.3.0-rc.2

Which is not the file in particular instead a list of all files going from 1.2.1 to 1.3.0-rc.2, accidentally switching the source. 

So the two bugs are:
1. The source switches
2. You can't view a file in particular

**Comment by navinpeiris** [comment]
Sorry for the late reply @udaysinghcode. Thanks for those, I'll get them all sorted out!
