### ISSUE TITLE
Add diff for 1.3 final

### ISSUE THREAD

**Issue by PhillippOhlandt** [navinpeiris/phoenix-diff#7]
Hey,

it would be nice if the diff for phoenix 1.3 final could be added.

**Comment by navinpeiris** [comment]
on it! it'll be up in a tick

**Comment by PhillippOhlandt** [comment]
Awesome, thanks! Based on the commits in the Phoenix repo, it should be just a little deletion in the `phoenix.css` file (from rc3 to final), But I want to make sure there are no other changes :)

**Comment by navinpeiris** [comment]
Tis done now @PhillippOhlandt, see: https://www.phoenixdiff.org/?source=1.2.4&target=1.3.0

**Comment by PhillippOhlandt** [comment]
Thanks! https://www.phoenixdiff.org/?source=1.3.0-rc.3&target=1.3.0 As I expected, just the CSS change and the version bump :)
